@startuml

database Book <<PostgreSQL>> as dbbook
database Gateway <<PostgreSQL>> as dbgateway
database ISBN <<PostgreSQL>> as dbisbn

actor Client as client
node Gateway <<Angular>> as gateway
node "Book API" as book
node "ISBN API" as isbn
node Keycloak as key
node "JHipster Registry" as registry
node LDAP as ldap

gateway -.> registry
book -.> registry
isbn -.> registry

book -.> dbbook
isbn -.> dbisbn
gateway .> dbgateway

book -> isbn

client -.> gateway
gateway -> book
gateway --> isbn

key -> ldap

@enduml
