@startuml

database Book <<PostgreSQL>> as dbbook
database Gateway <<PostgreSQL>> as dbgateway
database ISBN <<PostgreSQL>> as dbisbn

actor Client as client
node Gateway <<Angular>> as gateway
node "Book API" <<Spring>> as book
node "ISBN API" <<Spring>> as isbn
node Keycloak as key
node "JHipster Registry" <<Eureka>> as registry
node LDAP <<Apache DS>> as ldap

gateway -.> registry
book -.> registry
isbn -.> registry

book -.> dbbook
isbn -.> dbisbn
gateway .> dbgateway

book -> "Feign" isbn

client -.> gateway
gateway -> book
gateway --> isbn

key -> ldap

@enduml
